/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projeto16;

/**
 *
 * @author w.rocha
 */
public class NewJPanel_cadastroDeAdocao extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel_cadastroDeAdocao
     */
    public NewJPanel_cadastroDeAdocao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Jtxt_nomeAdotado11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jtxt_nomeAdotado = new javax.swing.JTextField();
        Jlbl_Data_Nascimento = new javax.swing.JLabel();
        Jtxt_nomeAdotado1 = new javax.swing.JTextField();
        Jlbl_Data_orfanato = new javax.swing.JLabel();
        Jtxt_NomeDoPaiAdotivo = new javax.swing.JTextField();
        Jlbl_CPFpaiAdotivo = new javax.swing.JLabel();
        Jtxt_nomeAdotado3 = new javax.swing.JTextField();
        Jlbl_NomeDaMaeAdotiva = new javax.swing.JLabel();
        Jtxt_CPFmaeAdotiva = new javax.swing.JTextField();
        Jlbl_NomeDoPaiAdotivo = new javax.swing.JLabel();
        Jtxt_NomeDaMaeAdotiva = new javax.swing.JTextField();
        Jlbl_CPFmaeAdotiva = new javax.swing.JLabel();
        Jtxt_CPFpaiAdotivo = new javax.swing.JTextField();
        Jlbl_CPFadotado = new javax.swing.JLabel();
        Jtxt_Renda = new javax.swing.JTextField();
        Jlbl_Renda = new javax.swing.JLabel();
        Jtxt_CPFadotado = new javax.swing.JTextField();
        Jlbl_IrmaosOuEnteados = new javax.swing.JLabel();
        Jc_IrmaosOuEnteados = new javax.swing.JComboBox<>();
        Jtxt_Endereco = new javax.swing.JTextField();
        Jlbl_endereco = new javax.swing.JLabel();
        Jtxt_CelularMae = new javax.swing.JTextField();
        Jlbl_celularPai = new javax.swing.JLabel();
        Jlbl_CelularMae = new javax.swing.JLabel();
        Jtxt_CelularPai = new javax.swing.JTextField();

        jLabel9.setText("CPF do adotado.");

        jLabel13.setText("Endereco");

        Jtxt_nomeAdotado11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_nomeAdotado11ActionPerformed(evt);
            }
        });

        jLabel14.setText("Número de celular do pai.");

        jLabel1.setText("Nome do adotado.");

        Jlbl_Data_Nascimento.setText("Data de nascimento.");

        Jlbl_Data_orfanato.setText("Data em que chegou ao orfanato.");

        Jlbl_CPFpaiAdotivo.setText("CPF do pai adotivo.");

        Jlbl_NomeDaMaeAdotiva.setText("Nome completo da mae adotiva.");

        Jlbl_NomeDoPaiAdotivo.setText("Nome completo do pai adotivo.");

        Jlbl_CPFmaeAdotiva.setText("CPF da mãe adotiva.");

        Jtxt_CPFpaiAdotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_CPFpaiAdotivoActionPerformed(evt);
            }
        });

        Jlbl_CPFadotado.setText("CPF do adotado.");

        Jtxt_Renda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_RendaActionPerformed(evt);
            }
        });

        Jlbl_Renda.setText("Renda mensal da família.");

        Jtxt_CPFadotado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_CPFadotadoActionPerformed(evt);
            }
        });

        Jlbl_IrmaosOuEnteados.setText("Possui irmãos, ou enteados.");

        Jc_IrmaosOuEnteados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        Jc_IrmaosOuEnteados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jc_IrmaosOuEnteadosActionPerformed(evt);
            }
        });

        Jtxt_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_EnderecoActionPerformed(evt);
            }
        });

        Jlbl_endereco.setText("Endereco:");

        Jtxt_CelularMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_CelularMaeActionPerformed(evt);
            }
        });

        Jlbl_celularPai.setText("Número de celular do pai.");

        Jlbl_CelularMae.setText("Número de celular da mãe.");

        Jtxt_CelularPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_CelularPaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlbl_CPFpaiAdotivo)
                            .addComponent(Jtxt_CPFpaiAdotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jlbl_NomeDoPaiAdotivo)
                            .addComponent(Jtxt_NomeDoPaiAdotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(Jlbl_NomeDaMaeAdotiva)
                            .addComponent(Jtxt_NomeDaMaeAdotiva))
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlbl_endereco, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Jtxt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Jlbl_celularPai, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Jtxt_nomeAdotado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jtxt_CPFmaeAdotiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jlbl_Data_orfanato)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Jtxt_nomeAdotado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jlbl_Data_Nascimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Jtxt_nomeAdotado3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jlbl_CPFmaeAdotiva))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Jlbl_CPFadotado)
                                .addGap(188, 188, 188))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jlbl_Renda, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(Jlbl_IrmaosOuEnteados, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(Jlbl_CelularMae, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Jc_IrmaosOuEnteados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Jtxt_CPFadotado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Jtxt_Renda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Jtxt_CelularMae, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Jtxt_CelularPai, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Jlbl_CPFadotado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxt_nomeAdotado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtxt_CPFadotado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Jlbl_Data_Nascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxt_nomeAdotado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jlbl_Data_orfanato))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Jlbl_Renda)
                        .addGap(9, 9, 9)
                        .addComponent(Jtxt_Renda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jtxt_nomeAdotado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jlbl_IrmaosOuEnteados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jc_IrmaosOuEnteados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jlbl_NomeDoPaiAdotivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxt_NomeDoPaiAdotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jlbl_NomeDaMaeAdotiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxt_NomeDaMaeAdotiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jlbl_endereco)
                        .addGap(9, 9, 9)
                        .addComponent(Jtxt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(Jlbl_celularPai)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Jlbl_CPFmaeAdotiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxt_CPFmaeAdotiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Jtxt_CelularPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jlbl_CelularMae)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlbl_CPFpaiAdotivo)
                    .addComponent(Jtxt_CelularMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jtxt_CPFpaiAdotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Jtxt_CPFpaiAdotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_CPFpaiAdotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_CPFpaiAdotivoActionPerformed

    private void Jtxt_CPFadotadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_CPFadotadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_CPFadotadoActionPerformed

    private void Jtxt_RendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_RendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_RendaActionPerformed

    private void Jc_IrmaosOuEnteadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jc_IrmaosOuEnteadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jc_IrmaosOuEnteadosActionPerformed

    private void Jtxt_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_EnderecoActionPerformed

    private void Jtxt_nomeAdotado11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_nomeAdotado11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_nomeAdotado11ActionPerformed

    private void Jtxt_CelularMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_CelularMaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_CelularMaeActionPerformed

    private void Jtxt_CelularPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_CelularPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_CelularPaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jc_IrmaosOuEnteados;
    private javax.swing.JLabel Jlbl_CPFadotado;
    private javax.swing.JLabel Jlbl_CPFmaeAdotiva;
    private javax.swing.JLabel Jlbl_CPFpaiAdotivo;
    private javax.swing.JLabel Jlbl_CelularMae;
    private javax.swing.JLabel Jlbl_Data_Nascimento;
    private javax.swing.JLabel Jlbl_Data_orfanato;
    private javax.swing.JLabel Jlbl_IrmaosOuEnteados;
    private javax.swing.JLabel Jlbl_NomeDaMaeAdotiva;
    private javax.swing.JLabel Jlbl_NomeDoPaiAdotivo;
    private javax.swing.JLabel Jlbl_Renda;
    private javax.swing.JLabel Jlbl_celularPai;
    private javax.swing.JLabel Jlbl_endereco;
    private javax.swing.JTextField Jtxt_CPFadotado;
    private javax.swing.JTextField Jtxt_CPFmaeAdotiva;
    private javax.swing.JTextField Jtxt_CPFpaiAdotivo;
    private javax.swing.JTextField Jtxt_CelularMae;
    private javax.swing.JTextField Jtxt_CelularPai;
    private javax.swing.JTextField Jtxt_Endereco;
    private javax.swing.JTextField Jtxt_NomeDaMaeAdotiva;
    private javax.swing.JTextField Jtxt_NomeDoPaiAdotivo;
    private javax.swing.JTextField Jtxt_Renda;
    private javax.swing.JTextField Jtxt_nomeAdotado;
    private javax.swing.JTextField Jtxt_nomeAdotado1;
    private javax.swing.JTextField Jtxt_nomeAdotado11;
    private javax.swing.JTextField Jtxt_nomeAdotado3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
